### ISSUE TITLE
Mobs are not generated

### ISSUE THREAD

**Issue by HeberonYT** [Lykrast/DefiledLands#14]
**Minecraft version :**1.12.2

**Defiled Lands version :**defiledlands-1.12.2-1.2.0.jar

Hello
I found an incompatibility between your mod and the CustomMobSpawner from Mo'Creatures.
When those 3 mods are installed, DefiledLands biomes look totally empty, no mob is generated in them.
I checked the configuration of custommobspawner and it seems to be working fine, added a class to generate the entities of its mod but it does not seem to generate them.
![screenshot_1](https://user-images.githubusercontent.com/13698597/37249310-df38f7a0-24aa-11e8-9aa3-4fe4b735cbac.png)

**Comment by Lykrast** [comment]
I honestly have no idea how CustomMobSpawner works and don't really have the time to work on that mod for now.

Sorry the fix will have to wait for some time.

**Comment by HeberonYT** [comment]
Hi. 
Thanks for your response, I made some modifications to the configuration of CustonMobSpawner and I managed to generate all the mobs in vanilla biomes.
It seems that the problem is in the name of the biome, could you tell me what are the names of your biomes and also the name identifier of your mod?

**Comment by Lykrast** [comment]
In theory they are :

- `defiledlands:desert_defiled`
- `defiledlands:plains_defiled`
- `defiledlands:forest_tenebra`
- `defiledlands:forest_vilespine`
- `defiledlands:hills_defiled`
- `defiledlands:swamp_defiled`
- `defiledlands:ice_plains_defiled`

**Comment by slammaja** [comment]
Hey Heberon,
in this case I believe it's CustomMobSpawner's fault, the same happens with Abyssalcraft and CMS installed, even in some biomes of Biomes O'Plenty, CMS always caused problems for me since MC 1.6.4 (there I had no squids spawning).

**Comment by HeberonYT** [comment]
I appreciate your comment.
I agree with you, the problem caused by CustomMobSpawner, I made some changes in the settings and I managed to make the entities of the DefiledLands mod generate in a biome of the same mod, it could be Hills or Plains, but I never managed to make it work in all of the time.
Also, at each restart of the server, the CustomMobSpawner configuration changes and therefore stops working.
Everything points to CMS having problems to identify the biomes of other mods, and therefore does not create configurations to generate in them.

**Comment by Lykrast** [comment]
Alright then, I suggest you report that to CMS if you can.

**Comment by sHall0w** [comment]
> I appreciate your comment. I agree with you, the problem caused by CustomMobSpawner, I made some changes in the settings and I managed to make the entities of the DefiledLands mod generate in a biome of the same mod, it could be Hills or Plains, but I never managed to make it work in all of the time. Also, at each restart of the server, the CustomMobSpawner configuration changes and therefore stops working. Everything points to CMS having problems to identify the biomes of other mods, and therefore does not create configurations to generate in them.

This is kinda late, but could you (or anyone) please help me with this? I'm not an expert in such things and i have no idea how to solve this...
