### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/statemap/IStateMapper

### ISSUE THREAD

**Issue by iamtpage** [Lykrast/DefiledLands#15]
**Minecraft version :** 1.12.2

**Defiled Lands version :** 1.4.0

**Crash log :** https://gist.github.com/iamtpage/07dee9a3d25e80edb7d05dbd5146020e

**Comment by Lykrast** [comment]
Fixed in ffbbde199a5d5e23d00d6ca5ef5c6196d544a1c6

New version should be up on Curseforge as soon as it is accepted.
