### ISSUE TITLE
It spreads trough the whole world

### ISSUE THREAD

**Issue by Tetailla** [Lykrast/DefiledLands#16]
**Minecraft version :** 12.2

**Defiled Lands version :** 12.2

like the title says, it spreads tough the whole world! its totally stupid that it does that. we cant stop or controll it, it came to our base in like 2 minutes (irl) you said it would spread more then 2-3 blocks from their natural habbit, so what the heck happend there. fix it.

**Comment by Lykrast** [comment]
Check your config and tell me what value does `B:confinedSpread` has.

**Comment by Lykrast** [comment]
Tested on my own on the latest version, default generated config has `B:confinedSpread` correctly set to false which correctly prevents the defiled blocks from spreading out of their natural boundaries.
