### ISSUE TITLE
[Request] Add option to tone down volume/frequency of Book Wyrms

### ISSUE THREAD

**Issue by iamtpage** [Lykrast/DefiledLands#18]
**Minecraft version :**
1.12.2
**Defiled Lands version :**
defiledlands-1.12.2-1.4.1

I keep a few book wyms near my main area of work and they constantly hiss loudly, it has gotten to the point where I want to put them deep underground so I never have to hear the sound again. An option to reduce how often the sound plays and the volume of the hissing sound would be fantastic.

**Comment by Lykrast** [comment]
Will simply reduce their sound volume to a more acceptable level, and see if there's a way to make them make sounds less often.

**Comment by iamtpage** [comment]
As a workaround to anyone else: Turning off the friendly mob sounds in your settings silences them.

**Comment by Lykrast** [comment]
72c9fe0acbdc580b92b380f5088c91a9e0e61002 should fix it for next update. Issue will be closed once update is live (may be a small hotfix or change a few more things).
