### ISSUE TITLE
[1.12] Defiled Lands appears to be crashing the server on startup.

### ISSUE THREAD

**Issue by elucent** [Lykrast/DefiledLands#2]
Crash Report: https://gist.github.com/elucent/5da10504467d0c48f8f8b38ddd1d11de

Should be fixable by adding an `@SideOnly(Side.CLIENT)` [here](https://github.com/Lykrast/DefiledLands/blob/master/src/main/java/lykrast/defiledlands/common/item/ItemArmorGeneric.java#L25).

**Comment by Lykrast** [comment]
Should be fixed with https://github.com/Lykrast/DefiledLands/commit/0d5396039ac905751b21e9ba5175b96a1c804fa0.
