### ISSUE TITLE
Defilement doesn't spread itself to trees

### ISSUE THREAD

**Issue by Virtualistik** [Lykrast/DefiledLands#20]
**Minecraft version : 1.12.2**

**Defiled Lands version : 1.4.2**

If the defilement spreads to a vanilla tree, it will not be converted to tenebra wood and tenebra leaves.

**Comment by Lykrast** [comment]
Intended behavior, like blastems and vilespine, tenebras are a specie of tree that grows in the defiled lands, and not trees that got corrupted by it (unlike stone, dirt and all that stuff).

**Comment by Virtualistik** [comment]
ah fair enough! ^^ might try to make my own branch where it works the way i want then

thanks
