### ISSUE TITLE
There are no mobs in the Defiled Lands

### ISSUE THREAD

**Issue by sHall0w** [Lykrast/DefiledLands#30]
**Minecraft version : 1.12.2**

**Defiled Lands version : 1.12.2-1.4.3**

The title says it all. Everytime I enter the defiled lands it's completely empty, there are no defiled mobs  (I have the latest version of the mod). I had no idea why, until I found the exact same issue on the followng link, and although i read the comments under it, I honestly have no idea how to solve this, i'm not an expert with these things... Could anyone help me please? I'd be very grateful.

https://github.com/Lykrast/DefiledLands/issues/14

**Comment by Lykrast** [comment]
This previous issue had CustomMobSpawner and Mo'Creatures mods installed, and apparently CustomMobSpawner causes issues with the mob spawning. So if you have those mods installed then remove them and it should work.
