### ISSUE TITLE
Conjuring Altar Not Rendering Correctly

### ISSUE THREAD

**Issue by InsomniaKitten** [Lykrast/DefiledLands#5]
You aren't setting a `BlockRenderLayer` in `BlockConjuringAltar` so it doesn't render properly in the world.
It would need to be `CUTOUT` or `CUTOUT_MIPPED` for it to render as intended.

**Mod version:** [0.2.0](https://minecraft.curseforge.com/projects/defiled-lands/files/2461203)
**Forge version:** [1.12-14.21.1.2443](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2443/forge-1.12-14.21.1.2443-changelog.txt)

![Screenshot of Conjuring Altar](http://i.imgur.com/5c5PRwM.png)

**Comment by Lykrast** [comment]
That's weird as I never got this issue myself, and that's weird how the altars in your screenshots have diamonds as it's not supposed to have any.

Anyway, implemented the fix with https://github.com/Lykrast/DefiledLands/commit/90189da7cce5e23b43bda918eebcf0ba2b6781c2 as I don't see any harm with it, may wait for a bit as I'm preparing a bigger update.

**Comment by InsomniaKitten** [comment]
Oh! I found the issue on my end too. I was using [this resource pack here ](https://minecraft.curseforge.com/projects/ctp) which replaces the existing enchanting table model (which you're using), and the layer it was adding needed to be on the cutout layer, hence the whiteness on my screenshot. The easiest solution to avoid conflicts with other mods/resource packs would be to have your own altar model (just copy the vanilla enchanting table model)
