### ISSUE TITLE
[1.12] Can't summon Ravager boss on servers.

### ISSUE THREAD

**Issue by elucent** [Lykrast/DefiledLands#6]
**Minecraft version :**

1.12

**Defiled Lands version :**

0.2.0

**Crash log :** (link to pastebin or something similar, delete that line if it's not a crash)

https://gist.github.com/elucent/187179a731f01fbe272fb46d417b6f54

**Comment by Lykrast** [comment]
Turns out getBiome was client sided for some reason... so now it uses a Tile Entity to actually check the biome.

Also the boss is called The Destroyer, the Ravager is the weapon you can craft with its drops.

**Comment by elucent** [comment]
Slip of the tongue, thanks for the quick fix!
