### ISSUE TITLE
suggestion of new defiled blocks

### ISSUE THREAD

**Issue by Hypsellis** [Lykrast/DefiledLands#7]
I noticed many blocks haven't their defiled equivalent, I think it would be interesting to add them.
- gravel
- brick
- mossy stone and brick stone
- clay and hardened clay
- glass and glass pane (could be got by smelting defiled sand)

**Comment by Lykrast** [comment]
Defiled Gravel has been added.

**Comment by Hypsellis** [comment]
Thanks it looks nice. Defiled clay and hardened clay could be added too, it would enable you to make defiled mesa biome. I think defiled brick and glass could be added too.

**Comment by Lykrast** [comment]
Obscure Glass (which kinda acts as defiled Glass), Defiled Mossy Stone (for Moss Stone) and Defiled Mossy Stone Bricks (for Mossy Stone Bricks) are gonna be added in 1.10 version.

**Comment by Hypsellis** [comment]
Oh it's awesome. I would suggest defiled clay and hardened clay with the adding of defiled mesa, and obscure brick when smelting defiled clay.
